config/routes.rb
Rails.application.routes.draw do
  root 'parser#show'
  get 'fill' => 'parser#fill_base'
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parser_controller.rb
require 'open-uri'

class ParserController < ApplicationController

  def get_html(page)
    page_s = "/"
    page_s += "page" + page.to_s unless page == 1
    recieved_document = open('https://habrahabr.ru' + page_s, 'User-Agent' => 'firefox')
    html = Nokogiri::HTML(recieved_document)
  end

  def parse_articles
    articles_array = []
    (1...10).each do |page_number|
      page_html = get_html(page_number)
      articles  = page_html.css(".post_title")
      articles.each do |article|
        articles_array.push({"title" => article.text, "url" => article.first[1]})
      end
    end
    articles_array
  end

  def save_articles(articles_array)
    articles_array.each do |article|
      newbie = Article.new(article)
      newbie.save
    end
  end

  def fill_base
    articles = parse_articles
    save_articles(articles)
    redirect_to root_path  
  end

  def show
    @articles = Article.first(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parser/show.html.erb
<h3>Последние десять записей habr'а</h3>
<div> 
  <%= button_to "Заполнить таблицу", fill_path, method: :get  %> 
  <%= button_to "Обновить", root_path, method: :get %> 
</div>
<div>
  <% @articles.each do |article| %>
    <p><%= article.title %> </br>
    <%= link_to article.url, article.url %><p>
  <% end %>
</div>